version: "3.9"  
services:
  api:
    env_file:
      - .env
    container_name: crud_api
    build: .
    ports:
      - "3000:3000"
    volumes:
        - .:/home/crud-nest
        -  /home/crud-nest/node_modules  
      
  database:
    image: postgres
    container_name:  crud_api_db
    environment:
        POSTGRES_DB: "${POSTGRES_DB}"
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080